name: Deploy easygo to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/easygo
            git pull origin main

            # Install backend dependencies
            cd backend
            npm install --production
            cd ..

            # Build frontend
            cd frontend
            npm install
            npm run build  # outputs to dist/
            cd ..

            # Restart app
            pm2 restart easygo